name: video_player_flutter_lint
description: custom_lint rules for video_player_flutter best practices.
version: 0.1.0
homepage: https://github.com/vorzela/video_player_flutter
repository: https://github.com/vorzela/video_player_flutter
license: MIT

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.0
  custom_lint_builder: ^0.8.1

dev_dependencies:
  custom_lint: ^0.8.1
  lints: ^5.0.0
